name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to latest version (v4 as of March 2025)

      - name: Setup Node
        uses: actions/setup-node@v4 # Updated to latest version (v4)
        with:
          node-version: 18 # Consider upgrading to 20 if compatible with your app
          cache: 'npm' # Added caching for faster installs

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          # Optional: Add environment variables if needed for your Next.js build
          NEXT_PUBLIC_BASE_URL: "https://kiraduitraya.nuzulfikriesalam.me"

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: duit-raya-calculator
          directory: .next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Specify branch for preview deployments
          branch: ${{ github.ref_name }}